FROM node:22-alpine

WORKDIR /frontend

COPY ainfra_frontend/package.json ainfra_frontend/package-lock.json ./

RUN npm install

COPY ainfra_frontend ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
